const ADD_SUCCSESS = 'notes/ADD_SUCCSESS';
const DELETE_SUCCSESS = 'notes/DELETE_SUCCSESS';
const TOGGLE_COMPLETED = 'notes/TOGGLE_COMPLETED';
const CHANGE_FILTER = 'notes/CHANGE_FILTER';

const FETCH_REQUEST = 'notes/FETCH_REQUEST';
const FETCH_SUCCSESS = 'notes/FETCH_SUCCSESS';
const FETCH_ERROR = 'notes/FETCH_ERROR';

export default {
  ADD_SUCCSESS,
  DELETE_SUCCSESS,
  TOGGLE_COMPLETED,
  CHANGE_FILTER,
  FETCH_REQUEST,
  FETCH_SUCCSESS,
  FETCH_ERROR,
};